# Generated by Django 4.0.4 on 2022-05-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_orpheanimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrpheanImage',
        ),
    ]
